### ISSUE TITLE
Edit TRIBES code to be compatible with Ubuntu distribution

### ISSUE THREAD

**Issue by natwine** [aehrc/TRIBES#2]
on running TRIBES on Ubuntu system, user received following error

./gzvcf2plink: 8: ./gzvcf2plink: Syntax error: "(" unexpected.

This is most likely due to using /bin/sh syntax.

Please could you update TRIBES scripts to explicitly call bash shell with #!/bin/bash 

This should resolve the issue to make it suitable for all Linux distributions

**Comment by piotrszul** [comment]
Fixed but needs to be tested on ubuntu.
